### PR TITLE
Dual CTA

### PR DESCRIPTION
**Pull request by mfbx9da4**
Haven't fully checked this will work. Just implemented the minimum for you to review whether you like the suggested UI. Can finish on approval e.g. disabled / readOnly states. (Note: also added small animation which is hard to see with gif).

l7ccsbpeUY

### CODE REVIEW

**Comment by saljam** [comment]
thanks for having a crack at this! i think that's an interesting proposal. that said, i'm not sure i like the extra click to reveal the input box. i'd really like to keep the interactions/steps at a minimum.

i recently pushed a bunch of changes to the way the first screen is worded. i'm hoping with more text in the prompt we can be less confusing. i'll try to solicit feedback from folks who have never used it.

**Comment by mfbx9da4** [comment]
I would argue that most people don't read instructions (🙈). Secondly, [users spend most of their time on other sites. This means that users prefer your site to work the same way as all the other sites they already know](https://lawsofux.com/jakobs-law/). Dual CTA pattern is common among many of the most popular websites.

image
image
image
image
image

Nevertheless, I appreciate the review and the final say is yours of course!

**Comment by saljam** [comment]
i'm coming round to accept we might need dual cta :)

however, i think joining & creating should get equal weight, both with minimum number of clicks. maybe vertically split the screen between both?

**Comment by mfbx9da4** [comment]
Yeah makes sense. I think something close to Instagram or Facebook in the screenshots above with the OR divider. Importantly, the CTA of join should be grouped with its input maybe like Twitter bootstraps 'input button addon’. I personally don’t mind an extra tap or click if it simplifies the UI and UX. I still love the morphing button concept and haven’t found an opportunity to use yet https://tympanus.net/Development/ButtonComponentMorph/

**Pull request closed without merging**
