### PR TITLE
go:generate as alternative to build/Makefile

### PR DESCRIPTION
**Pull request by dncohen**
I suggest `go generate` as an alternative (or in addition to) build script or Makefile.

### CODE REVIEW

**Comment by saljam** [comment]
thanks, i actually prefer this to the makefile. could you please move it to the top of (the terribly named) /web/util_js.go to avoid the relative paths?

we can remove build tags so that `go generate` would work on that too.

**Comment by dncohen** [comment]
My thought was its the `ww` executable that needs to serve the wasm.  If I were to move it, perhaps to the root, where one could `go generate ./... && go build ./...`?

Yeah, I thought of naming it webwormhole.wasm, but I didn't want to change too much in one PR.

**Comment by dncohen** [comment]
In my projects I tend to put a doc.go in the root.  And in that, I use go:generate to build a README.md and also whatever else is appropriate via go:generate.

**Comment by dncohen** [comment]
I just put the go:generate into web/build.go.  No need to remove build tags on the wasm specific file.

**Comment by saljam** [comment]
Perfect, thanks!

Also, serving the web directory by any means (plain old http server, S3, or GH Pages) should work independently of the ww tool, as long as they use the same signalling server. In my head this make me want to keep its build instructions contained within it.

**Comment by dncohen** [comment]
So, as is, the build.go file breaks `go build ./...` The problem is the package has to be named `main` for wasm to build.  But the additional file make go try to build a `web` executable.

I think it starts to get kludgy to put the go:generate into the web directory itself.  I don't think we want an executable called `web` being built by `go build ./...`

**Comment by saljam** [comment]
Hm, fair point. I guess we can exclude `js,wasm` in the build tags for build.go, and change it to a non-main package.

**Comment by dncohen** [comment]
unfortunately, cannot do that if it sits side-by side with the other go file with `package main`.  I guess go errs on the side of caution, and checks the package names even when the build tags don't overlap.

**Comment by saljam** [comment]
Strange, I've done it elsewhere!

**Comment by dncohen** [comment]
You are correct!  I had a typo in my build tag comment the first time I tried it.
 updated.

**Comment by saljam** [comment]
Great! Sorry for making you kludge it :)

I'm hoping with golang/go#25612 this will get nicer. At least it's contained.

**Comment by dncohen** [comment]
Cool.  Its not kludgy with the build tags right.  I'm pretty new to go's wasm support.  This project is great example to learn from.  You've combined a variety of pieces together very nicely!

**Pull request merged**
